version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gymbro-net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    depends_on:
      - db
    networks:
      - gymbro-net
    ports:
      - "9000:9000"
    volumes:
      - ./api:/var/www
      - ./api/storage:/var/www/storage  # Asegúrate de que se monte la carpeta storage
      - ./api/bootstrap/cache:/var/www/bootstrap/cache  # Monta la caché de bootstrap

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - gymbro-net
    volumes:
      - ./frontend:/app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    networks:
      - gymbro-net
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./api:/var/www
    depends_on:
      - api
    networks:
      - gymbro-net

networks:
  gymbro-net:

volumes:
  db_data:
